[build-system]
requires = ["setuptools>=65.5.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "acetele"
version = "0.1.0"
description = "A real-time remote teleoperation system for controlling robotic platforms."
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
    { name = "Xiangyuan Xie", email = "dragonboat_xxy@163.com" }
]
keywords = ["python", "robotic", "teleoperation"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
requires-python = ">=3.9"
dependencies = [
    "h5py",
    "loguru",
    "numpy",
    "pin",
    "pygame",
    "pyserial",
    "tomli",
    "tqdm",
]

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
"acetele.config" = ["*.toml"]

[tool.pytest.ini_options]
testpaths = ["tests"]
norecursedirs = ["acetele/deploy/realsense-ros"]
