[build-system]
requires = ["setuptools>=59.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "acetele"
version = "0.2.0"
description = "A real-time remote teleoperation system for controlling robotic platforms."
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
    { name = "Xiangyuan Xie", email = "dragonboat_xxy@163.com" }
]
license = { text = "Apache-2.0" }
keywords = ["python", "robotic", "teleoperation"]
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
requires-python = ">=3.10"
dependencies = [
    "loguru",
    "numpy",
    "pin",
    "pygame",
    "pyserial",
    "tomli",
    "tqdm",
]

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
where = ["."]
include = ["acetele*"]
exclude = [
    "build*",
    "tests*",
]

[tool.setuptools.package-data]
"acetele.config" = ["presets/ace_leader/*.toml", "presets/ace_follower/*.toml"]
"acetele.model.robots.ace_follower" = ["description/*.urdf", "description/meshes/*.STL"]
"acetele.model.robots.ace_leader" = ["description/*.urdf", "description/*.xml", "description/meshes/*.STL"]

[tool.pytest.ini_options]
testpaths = ["tests"]
norecursedirs = ["third_party"]
