[basic]
model = "ace_leader"
backend = "physical"
urdf_path = "../../../model/robots/ace_leader/description/ace_leader.urdf"

[buses.arm]
type = "feetech_packet"
port = "/dev/ttyUSB0"
baudrate = 1000000
cycle_hz = 100
direction_control = "auto"
physical_layer = "ttl"
family = "hls"
external_estop = true
allow_unverified_identity = true

[arms.single]
bus = "arm"
tool_frame = "link_5"

[[arms.single.joints]]
name = "joint_1"
servo_id = 0
servo_model = "HL3915"
direction = 1
home_position_rad = 0.0

[[arms.single.joints]]
name = "joint_2"
servo_id = 1
servo_model = "HL3915"
direction = -1
home_position_rad = 0.0

[[arms.single.joints]]
name = "joint_3"
servo_id = 2
servo_model = "HL3915"
direction = -1
home_position_rad = 0.0

[[arms.single.joints]]
name = "joint_4"
servo_id = 3
servo_model = "HL3915"
direction = -1
home_position_rad = 0.0

[arms.single.control]
adaptive_position = true
gravity_position = false

[arms.single.end_effector]
kind = "parallel_gripper"
bus = "arm"
travel_range_rad = 0.7853981633974483

[arms.single.end_effector.joint]
name = "joint_5"
servo_id = 4
servo_model = "HL3915"
direction = 1
home_position_rad = 0.0
