data_collector_node:
  ros__parameters:
    save_path: "~/data/"
    topics:
      - "^/ace_(leader|follower)/.*"
      - "^/fmu/.*"
      - "^/camera/(?!.*(compressed|theora)).*"
      - "^/Xie_1/.*"
