[basic]
station_type = "leader"

[linker.single]
port = "COM6"
joint_ids = [0, 1, 2, 3, 4]
gripper_ids = [4]
joint_signs = [1, 1, -1, -1, 1]
home_poses = [0.0, 0.0, 0.0, 0.0, 0.0]
dynamic_enable = true
servo_types = ["HL3915", "HL3915", "HL3915", "HL3915", "HL3915"]
