[basic]
model = "ace_follower"
backend = "physical"
urdf_path = "../../../model/robots/ace_follower/description/ace_follower.urdf"

[buses.arm]
type = "feetech_packet"
port = "/dev/ttyUSB0"
baudrate = 1000000
cycle_hz = 100
direction_control = "auto"
physical_layer = "rs485"
family = "sms"
external_estop = true

[arms.single]
bus = "arm"
tool_frame = "link_5"

[[arms.single.joints]]
name = "joint_1"
servo_id = 1
servo_model = "SM8512BL"
direction = 1
home_position_rad = 0.0

[[arms.single.joints]]
name = "joint_2"
servo_id = 2
servo_model = "SM8512BL"
direction = 1
home_position_rad = 0.0

[[arms.single.joints]]
name = "joint_3"
servo_id = 3
servo_model = "SM8512BL"
direction = 1
home_position_rad = 0.0

[[arms.single.joints]]
name = "joint_4"
servo_id = 4
servo_model = "SM8512BL"
direction = -1
home_position_rad = 0.0

[arms.single.control]
adaptive_position = true
