[basic]
robot_type = "ace_follower"
backend = "ros2"

[linker.single]
port = "/dev/ttyCH341USB0"
joint_ids = [0, 1, 2, 3]
joint_signs = [1, 1, 1, -1]
home_poses = [-1.57, 3.14, 0.0, 0.0]
enable_gravity_compensation = false
servo_types = ["HL3960", "HL3950", "HL3930", "HL3915"]

[gripper.single]
port = "/dev/ttyCH341USB0"
joint_id = 4
joint_sign = -1
home_pose = 1.0
servo_type = "HL3915"
gripper_type = "ace_follower"
