<?xml version="1.0"?>
<package format="3">
  <name>ace_robot_ros2</name>
  <version>0.0.1</version>
  <description>Unified ROS2 package for ACE robot (leader/follower) control</description>
  <maintainer email="dragonboat_xxy@163.com">Xiangyuan Xie</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>px4_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
